name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up nix
      run: sh <(curl -L https://nixos.org/nix/install) --daemon
    - name: Install nixos-install-tools
      run: nix-env -f '<nixpkgs>' -iA nixos-install-tools
