name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v30
    - name: Install nixos-install-tools
      run: |
        nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
        nix-env -f '<nixpkgs>' -iA nixos-install-tools
