name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - name: Install nixos-install-tools
      run: |
        nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
        nix-channel --update
        nix-env -f '<nixpkgs>' -iA nixos-install-tools
    - name: Set up disk image
      run: |
        sudo apt-get install qemu-utils -y
        sudo modprobe nbd max_part=16
        sudo qemu-img create -f qcow2 disk.qcow2 30g
        sudo qemu-nbd -c /dev/nbd0 disk.qcow2
    - name: Run disko
      run: |
        sed -i 's|/dev/nvme0n1|/dev/nbd0|g' disko.nix
        sudo `which nix` -v --experimental-features "nix-command flakes" run github:nix-community/disko/latest -- --mode disko disko.nix
    - name: Install NixOS
      run: |
        . /etc/profile.d/nix.sh
        export PATH="$PATH:/usr/sbin:/sbin"
        sudo PATH="$PATH" NIX_PATH="nixpkgs=channel:nixos-unstable" `which nixos-install` -v --flake .#nixos
    - name: Clean up
      run: |
        du -h disk.qcow2
        sudo swapoff -a
        sudo umount -r /mnt
        sudo qemu-nbd -d /dev/nbd0
        du -h disk.qcow2
        
